package com.flashinit {
	import com.berzerkrpg.MainGame;
	import com.berzerkrpg.constants.GameConstants;
	import com.berzerkrpg.io.BerzerkUserAPI;
	import com.berzerkrpg.io.Desktop_AdsController;
	import com.berzerkrpg.io.PlayerIOPaypalPremiumAPI;
	import com.berzerkrpg.io.playerio.ModelExternalPremiumAPIEnum;
	import com.lachhh.io.ExternalAPIManager;
	import com.lachhh.lachhhengine.VersionInfo;
	import com.lachhh.lachhhengine.sfx.Jukebox;
	import com.lachhhStarling.BerzerkAnimationManager;
	import com.lachhhStarling.ModelFlaEnum;
	import com.lachhhStarling.StarlingStage;
	import com.lachhhStarling.berzerk.BerzerkEmbeddedBitmapFonts;
	/**
	 * @author LachhhSSD
	 */
	public class ProfilerInit extends ReleaseInitDesktop {//DebugStarlingInitClean {
		public function ProfilerInit() {
			super();
			VersionInfo.isDebugPIO = false;	
			VersionInfo.hasDebugShortcut = true;
			VersionInfo.isDebug = true;
						
			VersionInfo.versionInfo = "v1.03.022";
			
			var berzerkPio:BerzerkUserAPI = new BerzerkUserAPI();
			berzerkPio.Connect(this);
			
			var paypalPremiumAPI:PlayerIOPaypalPremiumAPI = new PlayerIOPaypalPremiumAPI(berzerkPio);
			paypalPremiumAPI.Connect(this);
			
			ExternalAPIManager.premiumAPI = paypalPremiumAPI;
			
			ExternalAPIManager.pioAccount = berzerkPio;
			ExternalAPIManager.adsAPI = new Desktop_AdsController();
			VersionInfo.modelExternalAPI = ModelExternalPremiumAPIEnum.BERZERK;
			
			Jukebox.MUSIC_VOLUME = 0.5;
			Jukebox.SFX_VOLUME = 0.5;
		}

		override protected function startGame() : void {
			var b:BalancingXML = BalancingXML.loadFromStr(xml.toXMLString());
			GameConstants.getInstance().initFromBalancingXML(b);
			

			//ExternalAPIManager.proxyAnimationManager = new BerzerkAnimationManager(StarlingStage.instance);
			//textureLoader.loadFla(ModelFlaEnum.INTERFACE_TRANSITION);
			
			BerzerkEmbeddedBitmapFonts.loadFonts();
			
			var m:MainGame = new MainGame();
			stage.addChild(m);
			m.init();
			//TextFactory.importLangFromCSV();
			GameConstants.getInstance().loadEmbededData();
			//DataManagerAIR.loadDefaultBalancing();
			
			m.startQuickDebug();
			//m.startFromNormal();
			
			MobileSplashScreen.hide();
		}
		
	

		var xml : XML = <Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Misc>
		<id>misc1</id>
		<value>0.35</value>
	</Misc>
	<Misc>
		<id>misc2</id>
		<value>0.5</value>
	</Misc>
	<Misc>
		<id>misc3</id>
		<value>50</value>
	</Misc>
	<Misc>
		<id>misc4</id>
		<value>0.03</value>
	</Misc>
	<Misc>
		<id>misc5</id>
		<value>0.2</value>
	</Misc>
	<Misc>
		<id>misc6</id>
		<value>30</value>
	</Misc>
	<Misc>
		<id>misc7</id>
		<value>0.01</value>
	</Misc>
	<Misc>
		<id>misc8</id>
		<value>0.05</value>
	</Misc>
	<Misc>
		<id>misc9</id>
		<value>0.5</value>
	</Misc>
	<Misc>
		<id>misc10</id>
		<value>5</value>
	</Misc>
	<Misc>
		<id>misc11</id>
		<value>0.1</value>
	</Misc>
	<MapSpot>
		<id>mapSpot1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>0</difficultyStart>
		<difficultyEnd>20</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>20</difficultyStart>
		<difficultyEnd>40</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>40</difficultyStart>
		<difficultyEnd>60</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>50</difficultyStart>
		<difficultyEnd>70</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot5</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>60</difficultyStart>
		<difficultyEnd>80</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot6</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>80</difficultyStart>
		<difficultyEnd>100</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot7</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>120</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot8</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>120</difficultyStart>
		<difficultyEnd>140</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot9</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>140</difficultyStart>
		<difficultyEnd>170</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot10</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>170</difficultyStart>
		<difficultyEnd>200</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot11</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>180</difficultyStart>
		<difficultyEnd>210</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot12</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>200</difficultyStart>
		<difficultyEnd>240</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot13</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>210</difficultyStart>
		<difficultyEnd>260</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot14</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>250</difficultyStart>
		<difficultyEnd>280</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot15</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>270</difficultyStart>
		<difficultyEnd>300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot16</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>260</difficultyStart>
		<difficultyEnd>300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot17</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>280</difficultyStart>
		<difficultyEnd>300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot18</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>280</difficultyStart>
		<difficultyEnd>340</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot19</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>350</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpot20</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>400</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpotSecret1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>100</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpotSecret2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>200</difficultyStart>
		<difficultyEnd>200</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpotSecret3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>275</difficultyStart>
		<difficultyEnd>275</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapSpotSecret4</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>325</difficultyStart>
		<difficultyEnd>325</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1WizardBattle</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>450</difficultyStart>
		<difficultyEnd>450</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1KingChallenge</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>405</difficultyStart>
		<difficultyEnd>425</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1Challenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>115</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1Challenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>200</difficultyStart>
		<difficultyEnd>215</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1Challenge3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>315</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1Challenge2_1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>150</difficultyStart>
		<difficultyEnd>165</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1Challenge2_2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>250</difficultyStart>
		<difficultyEnd>265</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>50</difficultyStart>
		<difficultyEnd>200</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>200</difficultyStart>
		<difficultyEnd>300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>200</difficultyStart>
		<difficultyEnd>225</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>400</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot5</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>225</difficultyStart>
		<difficultyEnd>250</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot6</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>400</difficultyStart>
		<difficultyEnd>430</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot7</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>250</difficultyStart>
		<difficultyEnd>400</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot8</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>430</difficultyStart>
		<difficultyEnd>450</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot9</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>450</difficultyStart>
		<difficultyEnd>480</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot10</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>510</difficultyStart>
		<difficultyEnd>540</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot11</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>480</difficultyStart>
		<difficultyEnd>510</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Spot12</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>540</difficultyStart>
		<difficultyEnd>600</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2SpotSecret1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>425</difficultyStart>
		<difficultyEnd>425</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2SpotSecret2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>475</difficultyStart>
		<difficultyEnd>475</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2SpotSecret3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>700</difficultyStart>
		<difficultyEnd>700</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Challenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>350</difficultyStart>
		<difficultyEnd>365</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Challenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>315</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Challenge3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>450</difficultyStart>
		<difficultyEnd>500</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Challenge4</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>400</difficultyStart>
		<difficultyEnd>450</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Challenge5</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>325</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2Challenge6</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>325</difficultyStart>
		<difficultyEnd>340</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2WizardBattle</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>650</difficultyStart>
		<difficultyEnd>650</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map2KingChallenge</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>605</difficultyStart>
		<difficultyEnd>625</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>450</difficultyStart>
		<difficultyEnd>500</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>550</difficultyStart>
		<difficultyEnd>600</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>530</difficultyStart>
		<difficultyEnd>580</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>500</difficultyStart>
		<difficultyEnd>550</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot5</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>550</difficultyStart>
		<difficultyEnd>600</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot6</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>600</difficultyStart>
		<difficultyEnd>650</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot7</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>600</difficultyStart>
		<difficultyEnd>630</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot8</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>630</difficultyStart>
		<difficultyEnd>660</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot9</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>770</difficultyStart>
		<difficultyEnd>800</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot10</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>800</difficultyStart>
		<difficultyEnd>830</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot11</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>830</difficultyStart>
		<difficultyEnd>880</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot12</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>880</difficultyStart>
		<difficultyEnd>920</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot13</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>660</difficultyStart>
		<difficultyEnd>700</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot14</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>700</difficultyStart>
		<difficultyEnd>730</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot15</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>730</difficultyStart>
		<difficultyEnd>760</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot16</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>760</difficultyStart>
		<difficultyEnd>800</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot17</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>800</difficultyStart>
		<difficultyEnd>1000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Spot18</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1000</difficultyStart>
		<difficultyEnd>2000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3WizardBattle</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1050</difficultyStart>
		<difficultyEnd>1050</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3KingChallenge</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1005</difficultyStart>
		<difficultyEnd>1025</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3SpotSecret1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>600</difficultyStart>
		<difficultyEnd>600</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3SpotSecret2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>700</difficultyStart>
		<difficultyEnd>700</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3SpotSecret3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>750</difficultyStart>
		<difficultyEnd>750</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Challenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>650</difficultyStart>
		<difficultyEnd>665</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3Challenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>850</difficultyStart>
		<difficultyEnd>865</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map3PassportChallenge</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>730</difficultyStart>
		<difficultyEnd>755</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4challenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1000</difficultyStart>
		<difficultyEnd>1015</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4challenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1200</difficultyStart>
		<difficultyEnd>1215</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4challenge3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1300</difficultyStart>
		<difficultyEnd>1315</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4SpotSecret1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>950</difficultyStart>
		<difficultyEnd>950</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4SpotSecret2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1200</difficultyStart>
		<difficultyEnd>1200</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4SpotSecret3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1700</difficultyStart>
		<difficultyEnd>1700</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4WizardBattle</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>2050</difficultyStart>
		<difficultyEnd>2050</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4kingchallenge</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>2005</difficultyStart>
		<difficultyEnd>2025</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>800</difficultyStart>
		<difficultyEnd>1000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>850</difficultyStart>
		<difficultyEnd>1150</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>900</difficultyStart>
		<difficultyEnd>1100</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>900</difficultyStart>
		<difficultyEnd>1300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot5</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1000</difficultyStart>
		<difficultyEnd>1300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot6</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1200</difficultyStart>
		<difficultyEnd>1500</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot7</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1500</difficultyStart>
		<difficultyEnd>1750</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot8</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1750</difficultyStart>
		<difficultyEnd>1900</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot9</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1900</difficultyStart>
		<difficultyEnd>2000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map4Spot10</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1800</difficultyStart>
		<difficultyEnd>1900</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5challenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1850</difficultyStart>
		<difficultyEnd>1875</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5challenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>650</difficultyStart>
		<difficultyEnd>665</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5challenge3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>2600</difficultyStart>
		<difficultyEnd>2615</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5challenge4</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>2800</difficultyStart>
		<difficultyEnd>2815</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5SpotSecret1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>1750</difficultyStart>
		<difficultyEnd>1750</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5SpotSecret2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>2750</difficultyStart>
		<difficultyEnd>2750</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5SpotSecret3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>2500</difficultyStart>
		<difficultyEnd>2500</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5WizardBattle</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>3050</difficultyStart>
		<difficultyEnd>3050</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5kingchallenge</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>3005</difficultyStart>
		<difficultyEnd>3025</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5SpotBridgeChallenge</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1800</difficultyStart>
		<difficultyEnd>2000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1500</difficultyStart>
		<difficultyEnd>1800</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1800</difficultyStart>
		<difficultyEnd>2000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>1600</difficultyStart>
		<difficultyEnd>1900</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2000</difficultyStart>
		<difficultyEnd>2300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot5</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2000</difficultyStart>
		<difficultyEnd>2300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot6</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2200</difficultyStart>
		<difficultyEnd>2600</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot7</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2500</difficultyStart>
		<difficultyEnd>2800</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot8</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2750</difficultyStart>
		<difficultyEnd>2900</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot9</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2900</difficultyStart>
		<difficultyEnd>3000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map5Spot10</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>2900</difficultyStart>
		<difficultyEnd>3000</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventSpot1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>0</difficultyStart>
		<difficultyEnd>50</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventSpot2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>50</difficultyStart>
		<difficultyEnd>100</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventSpot3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>150</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventSpot4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>150</difficultyStart>
		<difficultyEnd>200</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventHalloweenChallenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>0</difficultyStart>
		<difficultyEnd>25</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventHalloweenChallenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>25</difficultyStart>
		<difficultyEnd>50</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventHalloweenChallenge3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>50</difficultyStart>
		<difficultyEnd>75</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventHalloweenChallenge4</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>75</difficultyStart>
		<difficultyEnd>100</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventHalloweenChallenge5</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>125</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventHalloweenChallenge6</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>125</difficultyStart>
		<difficultyEnd>150</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>map1Challenge1Thanksgiving2016</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>125</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventChristmas2016_1</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>150</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventChristmas2016_2</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>150</difficultyStart>
		<difficultyEnd>200</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventChristmas2016_3</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>200</difficultyStart>
		<difficultyEnd>250</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventChristmas2016_4</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>250</difficultyStart>
		<difficultyEnd>300</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventChristmas2016_5</id>
		<numUnitToKillPerArea>10</numUnitToKillPerArea>
		<difficultyStart>300</difficultyStart>
		<difficultyEnd>350</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventXmas2016_challenge1</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>125</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventXmas2016_challenge2</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>125</difficultyEnd>
	</MapSpot>
	<MapSpot>
		<id>mapEventXmas2016_challenge3</id>
		<numUnitToKillPerArea>1</numUnitToKillPerArea>
		<difficultyStart>100</difficultyStart>
		<difficultyEnd>125</difficultyEnd>
	</MapSpot>
	<Difficulty>
		<id>1</id>
		<rangeStart>1</rangeStart>
		<rangeEnd>50</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>2</id>
		<rangeStart>51</rangeStart>
		<rangeEnd>100</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>3</id>
		<rangeStart>101</rangeStart>
		<rangeEnd>150</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>4</id>
		<rangeStart>151</rangeStart>
		<rangeEnd>200</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>5</id>
		<rangeStart>201</rangeStart>
		<rangeEnd>250</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>6</id>
		<rangeStart>251</rangeStart>
		<rangeEnd>300</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>7</id>
		<rangeStart>301</rangeStart>
		<rangeEnd>350</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>8</id>
		<rangeStart>351</rangeStart>
		<rangeEnd>400</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>9</id>
		<rangeStart>401</rangeStart>
		<rangeEnd>450</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>10</id>
		<rangeStart>451</rangeStart>
		<rangeEnd>500</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.14</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>11</id>
		<rangeStart>501</rangeStart>
		<rangeEnd>550</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.13</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>12</id>
		<rangeStart>551</rangeStart>
		<rangeEnd>600</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.13</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>13</id>
		<rangeStart>601</rangeStart>
		<rangeEnd>650</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.13</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Difficulty>
		<id>14</id>
		<rangeStart>651</rangeStart>
		<rangeEnd>700</rangeEnd>
		<HPStart>10</HPStart>
		<HPLvl>1.13</HPLvl>
		<BossHpMul>5</BossHpMul>
		<MoneyStart>1</MoneyStart>
		<MoneyPerLvl>1.06</MoneyPerLvl>
		<MiniBossHPMul>4</MiniBossHPMul>
	</Difficulty>
	<Monsters>
		<id>monster1</id>
		<DPSStart>1</DPSStart>
		<CostStart>15</CostStart>
		<DPSxLVL>1.1</DPSxLVL>
		<CostxLvl>1.14</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>n/a</Skill2Bonus>
		<Skill3Bonus>dps+50%</Skill3Bonus>
		<Skill4Bonus>dpsPerLvl+1%</Skill4Bonus>
		<Skill1Cost>100</Skill1Cost>
		<Skill2Cost>500</Skill2Cost>
		<Skill3Cost>10000</Skill3Cost>
		<Skill4Cost>100000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster2</id>
		<DPSStart>1</DPSStart>
		<CostStart>50</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>dpsPerLvl+2%</Skill2Bonus>
		<Skill3Bonus>skull+5%</Skill3Bonus>
		<Skill4Bonus>dps+50%</Skill4Bonus>
		<Skill1Cost>100</Skill1Cost>
		<Skill2Cost>500</Skill2Cost>
		<Skill3Cost>1000</Skill3Cost>
		<Skill4Cost>10000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster3</id>
		<DPSStart>10</DPSStart>
		<CostStart>500</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>dpsPerLvl+2%</Skill2Bonus>
		<Skill3Bonus>dpsTotal+5%</Skill3Bonus>
		<Skill4Bonus>dps+50%</Skill4Bonus>
		<Skill1Cost>1000</Skill1Cost>
		<Skill2Cost>2000</Skill2Cost>
		<Skill3Cost>10000</Skill3Cost>
		<Skill4Cost>100000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster4</id>
		<DPSStart>100</DPSStart>
		<CostStart>5000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>n/a</Skill2Bonus>
		<Skill3Bonus>dps+50%</Skill3Bonus>
		<Skill4Bonus>dpsPerLvl+2%</Skill4Bonus>
		<Skill1Cost>10000</Skill1Cost>
		<Skill2Cost>20000</Skill2Cost>
		<Skill3Cost>100000</Skill3Cost>
		<Skill4Cost>1000000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster5</id>
		<DPSStart>1000</DPSStart>
		<CostStart>50000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>n/a</Skill2Bonus>
		<Skill3Bonus>dpsPerLvl+2%</Skill3Bonus>
		<Skill4Bonus>dps+50%</Skill4Bonus>
		<Skill1Cost>100000</Skill1Cost>
		<Skill2Cost>200000</Skill2Cost>
		<Skill3Cost>1000000</Skill3Cost>
		<Skill4Cost>10000000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster6</id>
		<DPSStart>10000</DPSStart>
		<CostStart>500000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>critHit+10%</Skill2Bonus>
		<Skill3Bonus>dps+50%</Skill3Bonus>
		<Skill4Bonus>dpsPerLvl+2%</Skill4Bonus>
		<Skill1Cost>1000000</Skill1Cost>
		<Skill2Cost>2000000</Skill2Cost>
		<Skill3Cost>10000000</Skill3Cost>
		<Skill4Cost>100000000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster7</id>
		<DPSStart>100000</DPSStart>
		<CostStart>5000000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>n/a</Skill2Bonus>
		<Skill3Bonus>dpsPerLvl+2%</Skill3Bonus>
		<Skill4Bonus>dps+50%</Skill4Bonus>
		<Skill1Cost>10000000</Skill1Cost>
		<Skill2Cost>20000000</Skill2Cost>
		<Skill3Cost>100000000</Skill3Cost>
		<Skill4Cost>1000000000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster8</id>
		<DPSStart>1000000</DPSStart>
		<CostStart>50000000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>dpsPerLvl+2%</Skill2Bonus>
		<Skill3Bonus>n/a</Skill3Bonus>
		<Skill4Bonus>dps+50%</Skill4Bonus>
		<Skill1Cost>100000000</Skill1Cost>
		<Skill2Cost>200000100</Skill2Cost>
		<Skill3Cost>1000000000</Skill3Cost>
		<Skill4Cost>10000000000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster9</id>
		<DPSStart>1000000000</DPSStart>
		<CostStart>50000000000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>n/a</Skill2Bonus>
		<Skill3Bonus>dpsPerLvl+2%</Skill3Bonus>
		<Skill4Bonus>dps+50%</Skill4Bonus>
		<Skill1Cost>1000000000</Skill1Cost>
		<Skill2Cost>2000000000</Skill2Cost>
		<Skill3Cost>10000000000</Skill3Cost>
		<Skill4Cost>100000000000</Skill4Cost>
	</Monsters>
	<Monsters>
		<id>monster10</id>
		<DPSStart>1000000000000</DPSStart>
		<CostStart>50000000000000</CostStart>
		<DPSxLVL>1.035</DPSxLVL>
		<CostxLvl>1.05</CostxLvl>
		<Skill1Bonus>dps+25%</Skill1Bonus>
		<Skill2Bonus>dpsPerLvl+2%</Skill2Bonus>
		<Skill3Bonus>dps+50%</Skill3Bonus>
		<Skill4Bonus>n/a</Skill4Bonus>
		<Skill1Cost>10000000000</Skill1Cost>
		<Skill2Cost>20000000000</Skill2Cost>
		<Skill3Cost>100000000000</Skill3Cost>
		<Skill4Cost>1000000000000</Skill4Cost>
	</Monsters>
	<ActiveSkills>
		<id>skill1</id>
		<bonus>n/a</bonus>
		<durationSec>5</durationSec>
		<cooldownSec>300</cooldownSec>
	</ActiveSkills>
	<ActiveSkills>
		<id>skill2</id>
		<bonus>n/a</bonus>
		<durationSec>60</durationSec>
		<cooldownSec>600</cooldownSec>
	</ActiveSkills>
	<ActiveSkills>
		<id>skill3</id>
		<bonus>n/a</bonus>
		<durationSec>90</durationSec>
		<cooldownSec>600</cooldownSec>
	</ActiveSkills>
	<ActiveSkills>
		<id>skill4</id>
		<bonus>n/a</bonus>
		<durationSec>120</durationSec>
		<cooldownSec>600</cooldownSec>
	</ActiveSkills>
	<ActiveSkills>
		<id>skill5</id>
		<bonus>n/a</bonus>
		<durationSec>150</durationSec>
		<cooldownSec>600</cooldownSec>
	</ActiveSkills>
	<ActiveSkills>
		<id>skill6</id>
		<bonus>n/a</bonus>
		<durationSec>180</durationSec>
		<cooldownSec>600</cooldownSec>
	</ActiveSkills>
	<ActiveSkills>
		<id>skill7</id>
		<bonus>n/a</bonus>
		<durationSec>210</durationSec>
		<cooldownSec>600</cooldownSec>
	</ActiveSkills>
	<MapSpotDifficulty>
		<id>mapSpot1</id>
		<hpStart>10</hpStart>
		<hpLvl>1.2</hpLvl>
		<bossHpMul>8</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.12</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot2</id>
		<hpStart>10</hpStart>
		<hpLvl>1.175</hpLvl>
		<bossHpMul>7</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.115</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot3</id>
		<hpStart>10</hpStart>
		<hpLvl>1.145</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.1</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot4</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.1</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot5</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.1</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot6</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.09</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot7</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.08</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot8</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.078</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot9</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>6</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.076</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot10</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.074</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot11</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.072</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot12</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.07</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot13</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.068</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot14</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.066</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot15</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.064</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot16</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.062</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot17</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.06</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot18</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.06</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot19</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.06</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpot20</id>
		<hpStart>10</hpStart>
		<hpLvl>1.14</hpLvl>
		<bossHpMul>5</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1.06</moneyLvl>
		<minibossHpMul>4</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpotSecret1</id>
		<hpStart>10000000</hpStart>
		<hpLvl>1</hpLvl>
		<bossHpMul>1</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1</moneyLvl>
		<minibossHpMul>1</minibossHpMul>
	</MapSpotDifficulty>
	<MapSpotDifficulty>
		<id>mapSpotSecret2</id>
		<hpStart>100000000</hpStart>
		<hpLvl>1</hpLvl>
		<bossHpMul>1</bossHpMul>
		<moneyStart>1</moneyStart>
		<moneyLvl>1</moneyLvl>
		<minibossHpMul>1</minibossHpMul>
	</MapSpotDifficulty>
</Root>;

	}
}
